using UnityEngine;
using System;

namespace Maskhot.Data
{
    /// <summary>
    /// Runtime quest data for a matching session
    /// Procedurally generated by QuestGenerator
    /// Combines a client (who is asking) with match criteria (what they want)
    /// </summary>
    [Serializable]
    public class Quest
    {
        [Tooltip("The client requesting this match")]
        public ClientProfile client;

        [Tooltip("What the client says when asking for help")]
        [TextArea(3, 6)]
        public string introductionText;

        [Tooltip("Criteria for finding a good match (presented to player as narrative hints)")]
        public MatchCriteria matchCriteria;

        /// <summary>
        /// Creates a quest from a curated ClientProfileSO
        /// </summary>
        public static Quest FromClientProfileSO(ClientProfileSO clientSO, string intro, MatchCriteria criteria)
        {
            return new Quest
            {
                client = clientSO.profile,
                introductionText = intro,
                matchCriteria = criteria
            };
        }

        /// <summary>
        /// Creates a fully procedural quest
        /// </summary>
        public static Quest CreateProcedural(ClientProfile proceduralClient, string intro, MatchCriteria criteria)
        {
            return new Quest
            {
                client = proceduralClient,
                introductionText = intro,
                matchCriteria = criteria
            };
        }
    }
}
